schema: 1
type: policy-context

id: config-recording-not-enabled
name: Config recording not enabled
labels:
  - contextualization

csp: aws
service: config
resource-type: config-recorder

class: risk
subclass: config
category: visibility
subcategory: logging

filters:
  - vendor: prisma-cloud
    policies:
      - "ca5c571e-6930-44af-a47b-ebde3ac20ca5"
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "ca5c571e-6930-44af-a47b-ebde3ac20ca5"

risk-config:
  default-risk: medium
