schema: 1
type: policy-context

id: cloudtrail-is-not-configured-for-all-regions
name: CloudTrail is not configured for all regions
labels:
  - contextualization

csp: aws
service: cloudtrail
resource-type: trail

class: risk
subclass: config
category: visibility
subcategory: logging

filters:
  - vendor: aws-config
    policies:
      - "multi-region-cloudtrail-enabled"
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("multi-region-cloudtrail-enabled"))

risk-config:
  default-risk: critical
