name: "*Prod Upgrade* CFT.yaml"
on:
  workflow_dispatch:
    inputs:
      tag:
        logLevel:
          description: 'git tag e.g. v1.0.0 to promote to prod'
          required: true


jobs:

  Copy-from-dev-to-prod:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: copy to prod path
        run: |
          aws s3 sync s3://${{ secrets.SAM_ARTIFACTS_BUCKET }}/${{ github.event.inputs.tag }}/ s3://${{ secrets.SAM_ARTIFACTS_BUCKET }}/latest/
