name: Publish Unit Test Coverage
on:
  push:
    paths:
      - "engine/**"
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: |
          cd engine
          mvn --no-transfer-progress --batch-mode test jacoco:report coveralls:report
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
